edit ctrl+num+num ability
ukad-group/timetracker-desktop-client pull request #120
Opened 2023-11-10 13:19 UTC by o-mehlii

2023-11-13 08:49 UTC, d-mashchenko commented on renderer/components/ActivitiesTable.tsx
> +            });
A can't add events from google if press ctrl + number

2023-11-15 09:06 UTC, a-nahaitsev requested changes

2023-11-16 08:25 UTC, a-nahaitsev approved these changes

2023-11-16 10:54 UTC, d-mashchenko approved these changes

2023-11-16 10:57 UTC, d-mashchenko commented
I would add ui/ux for the numbers. For example, you press 1 - it changes color in the first and tenth registration. The user must understand during the pause that something is happening.

2023-11-16 12:10 UTC, merged