web tracker year projects
ukad-group/timetracker-desktop-client pull request #121
Opened 2023-11-10 14:06 UTC by o-mehlii

2023-11-13 09:10 UTC, d-mashchenko requested changes

2023-11-13 09:10 UTC, d-mashchenko commented on renderer/components/TimetrackerWebsiteConncetion.tsx
>        localStorage.setItem("timetracker-user", JSON.stringify(userInfo));
you don't need to set in lcoalStorage "year-projects" bacause ive already added it in userInfo obj in 158 line, later in 160 i set it into localStorage.

2023-11-13 09:10 UTC, d-mashchenko commented on renderer/components/TimetrackerWebsiteConncetion.tsx
> +      localStorage.setItem("year-projects", loggedUser?.yearProjects.join(","));
You don't need to set in locastorage projects every time when components rerenders, localStorage save between reload etc.

2023-11-13 09:10 UTC, d-mashchenko commented on renderer/components/TrackTimeModal/TrackTimeModal.tsx
in general instead of setting projects only after user authorization, it is better to make a request for projects at the moment the modal window or select is opened. Projects may change over time, we need to somehow update the information.

2023-11-13 09:10 UTC, d-mashchenko commented on renderer/components/TrackTimeModal/TrackTimeModal.tsx
So, you don't need to set something in locastorage at all. Your projects should be received the moment you open the selector or modal.

2023-11-13 09:10 UTC, d-mashchenko commented on renderer/components/TrackTimeModal/TrackTimeModal.tsx
or may be in parent component, but the idea, i think, clear

2023-11-14 18:47 UTC, a-nahaitsev requested changes

2023-11-14 18:47 UTC, a-nahaitsev commented on renderer/components/TrackTimeModal/TrackTimeModal.tsx
> +      const yearProj = localStorage.getItem("year-projects").split(",");
let's split variables and conditions with empty string
Not only in this place. Everywhere when you see it.
It boosts code readability

2023-11-15 11:17 UTC, a-nahaitsev requested changes

2023-11-15 11:17 UTC, a-nahaitsev commented on electron-src/index.ts
> +
i guess we could optimize these two handlers. Why do we need to create new `fetch error` handler

2023-11-15 15:37 UTC, a-nahaitsev approved these changes

2023-11-17 08:34 UTC, merged