Feature/calendar-get-sum-of-working-hours
ukad-group/timetracker-desktop-client pull request #123
Opened 2023-11-13 07:02 UTC by d-mashchenko

- show required number of woking hours for month (with holidays and vacations)
- add icon with day off description near date cell in calendar

2023-11-14 16:06 UTC, o-mehlii reviewed
Only the first day of vacation is displayed in the calendar.

2023-11-15 09:59 UTC, a-nahaitsev requested changes

2023-11-15 09:59 UTC, a-nahaitsev commented on renderer/components/Calendar/Calendar.tsx
>    setSelectedDate: Dispatch<SetStateAction<Date>>;
let's rewrite name of constant with uppercase
https://www.javascripttutorial.net/es6/javascript-const/

2023-11-15 09:59 UTC, a-nahaitsev commented on renderer/components/Calendar/Calendar.tsx
> +      userPromises.push(...[holidaysPromise, vacationsPromise]);
if i'm not mistaken you can write it like this `userPromises.push(holidaysPromise, vacationsPromise);`

2023-11-15 09:59 UTC, a-nahaitsev commented on renderer/components/Calendar/Calendar.tsx
> +      });
i would move it to another function
i would return data from `loadHolidaysAndVacations` and moved this function to utils, file like timetracker.ts and import it here
what will you say?

2023-11-15 10:08 UTC, a-nahaitsev commented
Forgot to say
Can we load already reported hours from API and add current report hours until you load it?
Now you are calculating it from reports. But if one of them will be removed? or you changed your device and you have no reports for previous days. And also for previous months i see 0 in `Total`

2023-11-17 07:24 UTC, a-nahaitsev approved these changes

2023-11-17 07:32 UTC, merged