feature/line-copying-manual-input
ukad-group/timetracker-desktop-client pull request #145
Opened 2023-12-04 08:03 UTC by d-mashchenko

2023-12-04 10:56 UTC, o-mehlii approved these changes

2023-12-06 07:14 UTC, a-nahaitsev requested changes

2023-12-06 07:14 UTC, a-nahaitsev commented on renderer/utils/datetime-ui.ts
> +};
I have "AM/PM" when ctrl+d pressed. You should get rid of them 
![image](https://github.com/ukad-group/timetracker-desktop-client/assets/110410115/80f69fc8-d8d2-4bd1-8114-2394e60bdfd0)

2023-12-06 12:57 UTC, a-nahaitsev approved these changes

2023-12-06 13:09 UTC, merged