Feature/rework device theme toggle
ukad-group/timetracker-desktop-client pull request #147
Opened 2023-12-04 13:58 UTC by o-mehlii

2023-12-05 08:26 UTC, d-mashchenko commented on renderer/pages/settings.tsx
> +                      })
windows 11: it sets dark theme as system, although my system theme is light

2023-12-06 07:45 UTC, a-nahaitsev requested changes

2023-12-06 07:45 UTC, a-nahaitsev commented on renderer/pages/settings.tsx
i guess we should remove listener at the end of useEffect

2023-12-06 17:11 UTC, a-nahaitsev approved these changes

2023-12-07 11:01 UTC, merged