Fix/description deleting rework
ukad-group/timetracker-desktop-client pull request #151
Opened 2023-12-05 10:33 UTC by o-mehlii

2023-12-06 08:02 UTC, a-nahaitsev requested changes

2023-12-06 08:02 UTC, a-nahaitsev commented on renderer/components/ui/AutocompleteSelector.tsx
> +  const onBlurHandler = (e: ChangeEvent<HTMLInputElement>) => {
now projects/descriptions filtering doesn't work.

2023-12-06 13:48 UTC, d-mashchenko requested changes

2023-12-06 13:48 UTC, d-mashchenko commented on renderer/components/ui/AutocompleteSelector.tsx
> +  const onBlurHandler = (e: ChangeEvent<HTMLInputElement>) => {
also i can't see project from timtracker website

2023-12-08 12:41 UTC, a-nahaitsev commented on renderer/components/ui/AutocompleteSelector.tsx
>      }
i guess you should trim even you have spaces at the end
so i would remove condition
leave just
`e.target.value = e.target.value.trim();`

2023-12-08 13:10 UTC, merged