Fix/invalid date
ukad-group/timetracker-desktop-client pull request #186
Opened 2023-12-20 15:31 UTC by o-mehlii

2024-01-04 14:39 UTC, a-nahaitsev requested changes

2024-01-04 14:39 UTC, a-nahaitsev commented on renderer/utils/datetime-ui.ts
> +  let dateArray = dateString.split("");
why `let`? Do you reassign variable `dateArray`?

2024-01-08 09:26 UTC, a-nahaitsev approved these changes

2024-01-09 13:44 UTC, okhmelevskyi approved these changes

2024-01-09 13:46 UTC, merged