manual input undo/redo handler
ukad-group/timetracker-desktop-client pull request #188
Opened 2023-12-21 10:37 UTC by o-mehlii

2024-01-04 12:00 UTC, a-nahaitsev requested changes

2024-01-04 12:00 UTC, a-nahaitsev commented on renderer/components/ManualInputForm.tsx
> +      console.log(currentValue);
remove console.log

2024-01-04 12:00 UTC, a-nahaitsev commented on renderer/components/ManualInputForm.tsx
> +      e.preventDefault();
If I'm not mistaken, To avoid duplicating code you can move preventDefault from each condition and write it above them

2024-01-04 13:52 UTC, a-nahaitsev requested changes

2024-01-04 13:55 UTC, a-nahaitsev commented on renderer/components/ManualInputForm.tsx
> +      e.preventDefault();
I've checked. I'm mistaken with this comment.

2024-01-08 13:12 UTC, a-nahaitsev requested changes
and one more comment i will write in slack channel

2024-01-09 13:25 UTC, a-nahaitsev approved these changes

2024-01-09 13:28 UTC, okhmelevskyi approved these changes

2024-01-09 18:36 UTC, merged