add breaks design
ukad-group/timetracker-desktop-client pull request #222
Opened 2024-02-01 11:23 UTC by o-mehlii

2024-02-02 17:16 UTC, a-nahaitsev approved these changes

2024-02-05 11:12 UTC, okhmelevskyi approved these changes

2024-02-05 11:13 UTC, okhmelevskyi requested changes

2024-02-05 11:13 UTC, okhmelevskyi commented on renderer/src/components/ActivitiesTable/components/MainViewTable.tsx
> +          /* {tableActivities[i].to != tableActivities[i + 1]?.from &&
Remove this commented code, please.

2024-02-05 11:29 UTC, merged