connections tracking
ukad-group/timetracker-desktop-client pull request #230
Opened 2024-02-07 14:28 UTC by o-mehlii

https://trello.com/c/H4XWpXn9/340-how-many-calendars-are-connected-metric

2024-02-07 14:47 UTC, a-nahaitsev approved these changes

2024-02-09 10:37 UTC, okhmelevskyi requested changes

2024-02-09 10:37 UTC, okhmelevskyi commented on renderer/src/components/Calendar/Calendar.tsx
> +      trackConnections("timetrackerWeb");
Create a constant for trackConnections args.
An example `const TRACK_CONNECTIONS = { TIMETRACKER_WEB: 'timetrackerWeb' ... };`

2024-02-09 10:37 UTC, okhmelevskyi commented on renderer/src/helpers/utils/google.ts
> +  trackConnections("google-calendar");
The same here.

2024-02-09 10:37 UTC, okhmelevskyi commented on renderer/src/helpers/utils/jira.ts
> +    trackConnections("jira");
The same here.

2024-02-09 10:37 UTC, okhmelevskyi commented on renderer/src/helpers/utils/office365.ts
> +  trackConnections("office365-calendar");
The same here.

2024-02-09 10:37 UTC, okhmelevskyi commented on renderer/src/helpers/utils/trello.ts
> +  trackConnections("trello");
The same here.

2024-02-09 10:37 UTC, okhmelevskyi commented on renderer/src/helpers/utils/utils.ts
> +export const trackConnections = (connectedName: string) => {
Could you please cover this new function with unit tests? And check all cases.

2024-02-12 08:55 UTC, okhmelevskyi approved these changes

2024-02-12 09:45 UTC, merged