Feature/main page refactoring
ukad-group/timetracker-desktop-client pull request #242
Opened 2024-02-15 16:36 UTC by o-mehlii

2024-02-19 09:20 UTC, okhmelevskyi requested changes

2024-02-19 09:20 UTC, okhmelevskyi commented on renderer/src/helpers/hooks/useTheme.ts
> +  function handleThemeChange(e) {
Could you, please, overwrite this function?
Example` const handleThemeChange = (e) = >  e.matches ?  setIsOSDarkTheme(true) :  setIsOSDarkTheme(false);`
OR
You could test e.matches inside `setIsOSDarkTheme(Boolean(e.matches))` - it should be tested.

2024-02-19 09:20 UTC, okhmelevskyi commented on renderer/src/components/MainPage/MainPage.tsx
> +    (async () => {
May I ask you to move the logic from the useEffect hook to a new function and invoke the function inside that useEffect hook? Name the function with a sense, please.

2024-02-19 16:52 UTC, a-nahaitsev requested changes

2024-02-19 16:52 UTC, a-nahaitsev commented on renderer/src/components/MainPage/MainPage.tsx
> +    global.ipcRenderer.on("file-changed", (event, data) => {
move `file-changed` to constants

2024-02-19 16:52 UTC, a-nahaitsev commented on renderer/src/components/MainPage/MainPage.tsx
> +    global.ipcRenderer.on("errorMes", (event, data) => {
i guess, the same

2024-02-19 16:52 UTC, a-nahaitsev commented on renderer/src/components/MainPage/MainPage.tsx
> +      global.ipcRenderer.send(IPC_MAIN_CHANNELS.STOP_PATH_WATCHER, reportsFolder, selectedDate);
i guess, the same here

2024-02-20 08:56 UTC, a-nahaitsev requested changes

2024-02-20 08:56 UTC, a-nahaitsev commented on renderer/src/components/MainPage/MainPage.tsx
> +  const isManualInputMain = localStorage.getItem("is-manual-input-main-section") === "true";
Move to constants `is-manual-input-main-section`

2024-02-20 08:56 UTC, a-nahaitsev commented on renderer/src/components/MainPage/MainPage.tsx
> +    global.ipcRenderer.invoke("app:write-day-report", reportsFolder, selectedDate, serializedReport);
move to constants `app:write-day-report`

2024-02-20 08:56 UTC, a-nahaitsev commented on renderer/src/components/SelectFolderPlaceholder/SelectFolderPlaceholder.tsx
> +        setReportsFolder(folder);
`app:select-folder` on the line 12 - move it to constants as well

2024-02-20 09:24 UTC, okhmelevskyi approved these changes

2024-02-20 09:52 UTC, a-nahaitsev approved these changes

2024-02-21 15:15 UTC, merged